"""add expire_at login_attempts table

Revision ID: 6678005eb358
Revises: 694ab301a5de
Create Date: 2025-06-19 15:04:53.943688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6678005eb358'
down_revision: Union[str, None] = '694ab301a5de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_login_attempts', sa.Column('expire_at', sa.DateTime(), nullable=True, comment='expire time'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_login_attempts', 'expire_at')
    # ### end Alembic commands ###
