"""user, prompt table

Revision ID: 694ab301a5de
Revises: 4f4e8bb24492
Create Date: 2025-06-19 11:01:09.178249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '694ab301a5de'
down_revision: Union[str, None] = '4f4e8bb24492'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_prompts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='prompt ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='userID'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='title'),
    sa.Column('prompt', sa.Text(), nullable=False, comment='prompt'),
    sa.Column('schedule_frequency', sa.String(length=255), nullable=False, comment='daily or weekly'),
    sa.Column('schedule_time', sa.Time(), nullable=False, comment='schedule time like 08:00AM'),
    sa.Column('schedule_repeat_period', sa.Integer(), nullable=True, comment='repeat weeks period'),
    sa.Column('schedule_week_day', sa.ARRAY(sa.String()), nullable=True, comment='Array of weekdays like ["Mon", "Tue"]'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='True or False'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='created date'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='updated date'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='deleted date'),
    sa.ForeignKeyConstraint(['user_id'], ['m_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_prompt_recipients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='prompt recipient ID'),
    sa.Column('prompt_id', sa.Integer(), nullable=False, comment='Linked Prompt ID'),
    sa.Column('recipient_id', sa.Integer(), nullable=False, comment='Recipient User ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='created date'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='updated date'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='deleted date'),
    sa.ForeignKeyConstraint(['prompt_id'], ['t_prompts.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['m_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prompt_id', 'recipient_id', name='uq_prompt_recipient')
    )
    op.create_table('t_prompt_transaction_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='transaction history ID'),
    sa.Column('prompt_recipient_id', sa.Integer(), nullable=False, comment='Prompt To Recipient ID'),
    sa.Column('status', sa.String(length=255), nullable=False, comment='status'),
    sa.Column('send_date', sa.DateTime(), nullable=True, comment='Prompt Send Date'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='created date'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='updated date'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='deleted date'),
    sa.ForeignKeyConstraint(['prompt_recipient_id'], ['t_prompt_recipients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_prompt_transaction_history')
    op.drop_table('t_prompt_recipients')
    op.drop_table('t_prompts')
    # ### end Alembic commands ###
