"""add t_blacklisted_tokens

Revision ID: b41df28ce5d8
Revises: 6678005eb358
Create Date: 2025-06-20 17:03:38.807775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b41df28ce5d8'
down_revision: Union[str, None] = '6678005eb358'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_blacklisted_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expiry_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='created date'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='updated date'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='deleted date'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_blacklisted_tokens_id'), 't_blacklisted_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_t_blacklisted_tokens_token'), 't_blacklisted_tokens', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_t_blacklisted_tokens_token'), table_name='t_blacklisted_tokens')
    op.drop_index(op.f('ix_t_blacklisted_tokens_id'), table_name='t_blacklisted_tokens')
    op.drop_table('t_blacklisted_tokens')
    # ### end Alembic commands ###
