import { ICountry } from "./definition";

export const countries: ICountry[] = [
  { code: "+1", name: "United States", iso: "us" },
  { code: "+1", name: "Canada", iso: "ca" },
  { code: "+44", name: "United Kingdom", iso: "gb" },
  { code: "+33", name: "France", iso: "fr" },
  { code: "+49", name: "Germany", iso: "de" },
  { code: "+39", name: "Italy", iso: "it" },
  { code: "+34", name: "Spain", iso: "es" },
  { code: "+31", name: "Netherlands", iso: "nl" },
  { code: "+41", name: "Switzerland", iso: "ch" },
  { code: "+43", name: "Austria", iso: "at" },
  { code: "+32", name: "Belgium", iso: "be" },
  { code: "+45", name: "Denmark", iso: "dk" },
  { code: "+46", name: "Sweden", iso: "se" },
  { code: "+47", name: "Norway", iso: "no" },
  { code: "+358", name: "Finland", iso: "fi" },
  { code: "+351", name: "Portugal", iso: "pt" },
  { code: "+30", name: "Greece", iso: "gr" },
  { code: "+48", name: "Poland", iso: "pl" },
  { code: "+420", name: "Czech Republic", iso: "cz" },
  { code: "+36", name: "Hungary", iso: "hu" },
  { code: "+7", name: "Russia", iso: "ru" },
  { code: "+81", name: "Japan", iso: "jp" },
  { code: "+82", name: "South Korea", iso: "kr" },
  { code: "+86", name: "China", iso: "cn" },
  { code: "+91", name: "India", iso: "in" },
  { code: "+65", name: "Singapore", iso: "sg" },
  { code: "+852", name: "Hong Kong", iso: "hk" },
  { code: "+886", name: "Taiwan", iso: "tw" },
  { code: "+60", name: "Malaysia", iso: "my" },
  { code: "+66", name: "Thailand", iso: "th" },
  { code: "+84", name: "Vietnam", iso: "vn" },
  { code: "+63", name: "Philippines", iso: "ph" },
  { code: "+62", name: "Indonesia", iso: "id" },
  { code: "+61", name: "Australia", iso: "au" },
  { code: "+64", name: "New Zealand", iso: "nz" },
  { code: "+27", name: "South Africa", iso: "za" },
  { code: "+20", name: "Egypt", iso: "eg" },
  { code: "+234", name: "Nigeria", iso: "ng" },
  { code: "+254", name: "Kenya", iso: "ke" },
  { code: "+55", name: "Brazil", iso: "br" },
  { code: "+52", name: "Mexico", iso: "mx" },
  { code: "+54", name: "Argentina", iso: "ar" },
  { code: "+56", name: "Chile", iso: "cl" },
  { code: "+57", name: "Colombia", iso: "co" },
  { code: "+51", name: "Peru", iso: "pe" },
  { code: "+58", name: "Venezuela", iso: "ve" },
  { code: "+971", name: "UAE", iso: "ae" },
  { code: "+966", name: "Saudi Arabia", iso: "sa" },
  { code: "+972", name: "Israel", iso: "il" },
  { code: "+90", name: "Turkey", iso: "tr" },
];
